name: Build

on: [repository_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: intel/llvm
          ref: sycl
          modules: recursive

      - uses: lukka/get-cmake@latest
      - uses: Jimver/cuda-toolkit@master
      - run: python ./buildbot/configure.py --cuda -t Release
      - run: python ./buildbot/compile.py

      - uses: actions/upload-artifact@v4
        with:
          name: dpcpp
          path: build
          retention-days: 1
          compression-level: 9
          overwrite: true

